allowBuilds:
  '@parcel/watcher': true
  '@swc/core': true
  esbuild: true
  less: true
  lmdb: true
  msgpackr-extract: true
  nx: true
  unrs-resolver: true
autoInstallPeers: true
minimumReleaseAgeExclude:
  - playwright-core@1.63.0
  - playwright@1.63.0
  - "@playwright/test@1.63.0"
  - jose@6.2.12
